import SwiftUI

// v2.9.76：全局语言切换（中/英）
// 整个 App 主要界面文本跟随切换，默认中文
// 实现：内置字典映射，不依赖 .strings 文件（CI swift build 不编译 strings）

enum AppLanguage: String, CaseIterable {
    case zh = "zh"
    case en = "en"

    var displayName: String {
        switch self {
        case .zh: return "中文"
        case .en: return "English"
        }
    }
}

final class LanguageManager: ObservableObject {
    static let shared = LanguageManager()

    @Published var language: AppLanguage {
        didSet {
            UserDefaults.standard.set(language.rawValue, forKey: "app_language")
        }
    }

    private init() {
        let raw = UserDefaults.standard.string(forKey: "app_language") ?? "zh"
        language = AppLanguage(rawValue: raw) ?? .zh
    }

    var isZh: Bool { language == .zh }
}

enum L10n {
    static func t(_ key: String) -> String {
        let lang = LanguageManager.shared.language.rawValue
        let table: [String: [String: String]] = [
            // ===== 通用 =====
            "settings": ["zh": "设置", "en": "Settings"],
            "back": ["zh": "返回", "en": "Back"],
            "done": ["zh": "完成", "en": "Done"],
            "cancel": ["zh": "取消", "en": "Cancel"],
            "save": ["zh": "保存", "en": "Save"],
            "close": ["zh": "关闭", "en": "Close"],
            "delete": ["zh": "删除", "en": "Delete"],
            "copy": ["zh": "复制", "en": "Copy"],
            "share": ["zh": "分享", "en": "Share"],
            "version": ["zh": "版本", "en": "Version"],
            "language": ["zh": "语言", "en": "Language"],
            "search": ["zh": "搜索", "en": "Search"],
            "refresh": ["zh": "刷新", "en": "Refresh"],
            "confirm": ["zh": "确定", "en": "OK"],
            "warning": ["zh": "提示", "en": "Notice"],
            "enabled": ["zh": "已开启", "en": "On"],
            "disabled": ["zh": "已关闭", "en": "Off"],
            // v2.9.79：聊天框模型条
            "current_model": ["zh": "当前模型", "en": "Model"],
            "not_configured": ["zh": "未配置", "en": "Not set"],
            // v2.9.82：任务完成通知
            "task_notify": ["zh": "任务完成通知", "en": "Task Notification"],
            "task_notify_sub": ["zh": "AI 执行完成/失败时，后台发本地通知", "en": "Notify when AI finishes or fails in background"],
            // v2.9.85：推荐中转站卡片
            "relay_card_title": ["zh": "推荐中转站 · 作者自用", "en": "Recommended Relay · Author's Pick"],
            "relay_card_body": ["zh": "价格极低，作者本人就在用。这不是合作广告——通过链接注册会为作者增加 Token 额度，用于持续开发与更新更多功能。感谢支持！", "en": "Extremely low pricing, and it's the relay the author personally uses. This is not a sponsored ad — registering via the link adds tokens for the author to keep developing and shipping new features. Thanks for your support!"],
            "relay_card_copy": ["zh": "复制链接", "en": "Copy Link"],
            "relay_card_copied": ["zh": "已复制", "en": "Copied"],
            // v2.9.86：关于作者
            "about_title": ["zh": "关于作者", "en": "About Author"],
            "about_subtitle": ["zh": "ZeenAE · 独立开发者", "en": "ZeenAE · Independent Developer"],
            "about_bio": ["zh": "一个喜欢折腾 iOS 的独立开发者 🛠️ 相信“手机上就该能搞定一切”。TrollAgent 把注入、线上编译、测试、自动化这些原本要电脑 + 越狱才能做的事，全部搬进一台不越狱、只装 TrollStore 的 iPhone 里。持续迭代中，你的每次使用都是这个项目继续更新的动力 💪", "en": "An indie developer who loves tinkering with iOS 🛠️ and believes everything should be doable on a phone. TrollAgent brings injection, cloud builds, testing and automation — things that used to need a computer and a jailbreak — into one non-jailbroken iPhone with TrollStore. Iterating constantly; every use of yours keeps this project alive 💪"],
            "about_thanks": ["zh": "开源致谢", "en": "Open Source Credits"],
            "about_thanks_intro": ["zh": "感谢以下开源项目与作者：", "en": "Thanks to these open-source projects & authors:"],
            "about_thanks_all": ["zh": "以及所有开源社区的贡献者", "en": "and every open-source contributor"],
            "about_safety": ["zh": "安全说明", "en": "Security"],
            "about_safety_rows": ["zh": "🔒 所有操作均在本机完成，不收集、不上传任何个人信息。|🔑 API Key 仅保存在本机文稿目录，请求只发往你自己配置的服务器地址。|🎯 注入与内存操作只作用于你明确指定的 App，内置备份可随时还原。", "en": "🔒 All operations run locally; no personal data is collected or uploaded.|🔑 API keys stay in the app's local Documents folder; requests go only to servers you configure.|🎯 Injection & memory operations target only apps you explicitly choose, with backups for rollback."],
            "about_notes": ["zh": "注意事项", "en": "Notes"],
            "about_note_rows": ["zh": "⚠️ 注入前请备份重要数据；目标 App 更新后可能需要重新注入。|⚠️ 部分操作需在 TrollStore 开启「编辑 Entitlements」后重装 App 生效。|⚠️ 请仅在你有权操作的设备与 App 上使用，勿用于盗版、破解或任何违法用途。", "en": "⚠️ Back up important data before injecting; app updates may require re-injection.|⚠️ Some operations need “Edit Entitlements” in TrollStore, then reinstalling the app.|⚠️ Use only on devices & apps you own. Not for piracy, cracking or illegal purposes."],
            "about_disclaimer": ["zh": "免责声明", "en": "Disclaimer"],
            "about_disclaimer_rows": ["zh": "🚫 本项目为个人项目，与任何商业公司、品牌无隶属或合作关系。|🚫 作者不对因使用本工具造成的任何直接或间接损失负责。|🚫 页面中的第三方链接（如推荐的中转站）仅供参考，作者与其无利益合作。", "en": "🚫 This is a personal project with no affiliation to any company or brand.|🚫 The author is not liable for any direct or indirect loss from using this tool.|🚫 Third-party links (e.g. the recommended relay) are for reference only; no business partnership."],
            "about_sponsor": ["zh": "赞助支持", "en": "Sponsor"],
            "about_sponsor_body": ["zh": "如果 TrollAgent 帮到了你，欢迎请作者喝杯咖啡 ☕（完全自愿，量力而行）", "en": "If TrollAgent helps you, feel free to buy the author a coffee ☕ (purely voluntary)"],
            "about_feedback": ["zh": "Bug 与功能反馈", "en": "Bug & Feature Requests"],
            "about_feedback_body": ["zh": "遇到问题或有好点子？点下方按钮复制反馈信息（版本 + 设备），附上截图发给作者 📮", "en": "Found a bug or have an idea? Tap below to copy your feedback info (version + device), attach screenshots and send to the author 📮"],
            "about_copy_feedback": ["zh": "复制反馈信息", "en": "Copy Feedback Info"],
            "about_copied": ["zh": "已复制，去粘贴吧", "en": "Copied"],

            // ===== 首页 =====
            "home_greeting": ["zh": "你好，我是 TrollAgent", "en": "Hi, I'm TrollAgent"],
            "home_subtitle": ["zh": "TrollStore 上的 AI 实验与 QA 工作台\n分析 · 注入 · 编译 · 控制", "en": "AI lab & QA workbench for TrollStore\nAnalyze · Inject · Build · Control"],
            "home_analyze_apps": ["zh": "分析我的应用", "en": "Analyze My Apps"],
            "home_analyze_apps_sub": ["zh": "扫描缓存、注入状态与已安装应用", "en": "Scan caches, injection state & installed apps"],
            "home_check_device": ["zh": "检查设备与内存", "en": "Check Device & Memory"],
            "home_check_device_sub": ["zh": "设备信息、可用容量与环境检测", "en": "Device info, storage & environment probe"],
            "home_empty_title": ["zh": "尚未配置模型", "en": "No model configured"],
            "home_empty_sub": ["zh": "请先在设置中添加 API 配置", "en": "Add an API config in Settings first"],
            "home_thinking": ["zh": "正在思考", "en": "Thinking"],
            "home_running_tool": ["zh": "正在执行工具", "en": "Running tool"],
            "home_round": ["zh": "第 {n}/{total} 轮", "en": "Round {n}/{total}"],
            // v2.9.78：首页快速引导区
            "home_quick_title": ["zh": "快速开始", "en": "Quick Start"],
            "home_quick_sub": ["zh": "点击卡片直接体验 · 也可输入自己的指令", "en": "Tap a card to try, or type your own"],
            "home_quick_compile": ["zh": "线上编译", "en": "Cloud Build"],
            "home_quick_compile_sub": ["zh": "GitHub 编译 tweak / IPA", "en": "Build tweak / IPA on GitHub"],
            "home_quick_inject": ["zh": "注入测试", "en": "Injection Test"],
            "home_quick_inject_sub": ["zh": "给 App 注入 dylib 并验证", "en": "Inject & verify a dylib"],
            "home_quick_memory": ["zh": "内存修改", "en": "Memory Tweak"],
            "home_quick_memory_sub": ["zh": "H5gg 式搜索与修改", "en": "H5gg-style search & patch"],
            "home_quick_ui": ["zh": "UI 控制", "en": "UI Control"],
            "home_quick_ui_sub": ["zh": "控制任意 App 界面", "en": "Drive any app's UI"],
            "home_quick_browser": ["zh": "内置浏览器", "en": "Built-in Browser"],
            "home_quick_browser_sub": ["zh": "网页操作与抓取", "en": "Browse & scrape pages"],
            "home_quick_automation": ["zh": "自动化", "en": "Automation"],
            "home_quick_automation_sub": ["zh": "定时任务与重试", "en": "Scheduled tasks & retries"],

            // ===== 新手引导（v2.9.78）=====
            "ob_skip": ["zh": "跳过", "en": "Skip"],
            "ob_next": ["zh": "下一步", "en": "Next"],
            "ob_done": ["zh": "开始使用", "en": "Get Started"],
            "ob_welcome_title": ["zh": "欢迎使用 TrollAgent", "en": "Welcome to TrollAgent"],
            "ob_welcome_sub": ["zh": "TrollStore 上的 AI 实验与 QA 工作台：一句话描述目标，AI 自动完成诊断、操作、验证与报告。", "en": "An AI lab for TrollStore: describe a goal, and AI handles diagnosis, actions, verification and reporting."],
            "ob_cap_title": ["zh": "它能做什么", "en": "What it can do"],
            "ob_cap1": ["zh": "线上编译 tweak / IPA 并下载注入", "en": "Cloud-build tweaks / IPAs, download & inject"],
            "ob_cap2": ["zh": "H5gg 式内存搜索与修改", "en": "H5gg-style memory search & patch"],
            "ob_cap3": ["zh": "读取界面树、点击输入，控制任意 App", "en": "Read UI tree, tap & type to drive any app"],
            "ob_cap4": ["zh": "内置浏览器、审计、自动化与知识库", "en": "Built-in browser, audit, automation & KB"],
            "ob_start_title": ["zh": "开始使用", "en": "Get Started"],
            "ob_start_sub": ["zh": "先到「设置 → 模型 API」添加你的中转站配置，然后回来试试下方的快捷卡片。", "en": "Add your relay API config under Settings → Model API, then try the quick cards below."],

            // ===== 抽屉 =====
            "drawer_title": ["zh": "对话", "en": "Chats"],
            "drawer_search": ["zh": "搜索对话内容...", "en": "Search conversations..."],
            "drawer_count": ["zh": "{n} 个本机对话", "en": "{n} conversations"],
            "drawer_delete": ["zh": "删除对话", "en": "Delete Chat"],
            "drawer_ready": ["zh": "就绪 · 可注入", "en": "Ready · Injectable"],
            "drawer_env_limited": ["zh": "环境受限 · 点按查看", "en": "Limited · Tap to view"],
            "drawer_probe": ["zh": "点按检测本机", "en": "Tap to probe"],

            // ===== 设置分组 =====
            "sec_models": ["zh": "模型", "en": "Models"],
            "sec_control": ["zh": "控制", "en": "Control"],
            "sec_build": ["zh": "线上编译", "en": "Cloud Build"],
            "sec_core": ["zh": "核心功能", "en": "Core"],
            "sec_dev": ["zh": "开发者选项", "en": "Developer"],
            "row_keepalive": ["zh": "后台常驻", "en": "Background Keep-Alive"],
            "row_keepalive_sub": ["zh": "静音保活 + 周期刷新，AI 长任务/等待结果时不被挂起", "en": "Silent audio keep-alive + BG refresh, stay alive during AI tasks"],
            "sec_security": ["zh": "安全", "en": "Security"],
            "sec_about": ["zh": "关于", "en": "About"],

            // ===== 设置行 =====
            "row_model_api": ["zh": "模型 API", "en": "Model API"],
            "row_data": ["zh": "数据管理", "en": "Data Management"],
            "row_dev_instructions": ["zh": "开发者指令", "en": "Developer Instructions"],
            "row_sys_prompts": ["zh": "系统指令", "en": "System Prompts"],
            "row_inject": ["zh": "注入与自动化", "en": "Injection & Automation"],
            "row_inject_sub": ["zh": "全应用 · 策略 · 自动化", "en": "Apps · Policy · Automation"],
            "row_remote": ["zh": "远程控制", "en": "Remote Control"],
            "row_remote_sub": ["zh": "AI 控制任意 App UI", "en": "AI controls any app UI"],
            "row_github": ["zh": "GitHub 账号", "en": "GitHub Account"],
            "row_downloads": ["zh": "下载管理", "en": "Downloads"],
            "row_dev_mode": ["zh": "开发者模式", "en": "Developer Mode"],
            "row_permissions": ["zh": "权限与自动化", "en": "Permissions & Automation"],
            "row_automation": ["zh": "自动化中心", "en": "Automation Center"],
            "row_tool_policy": ["zh": "工具权限策略", "en": "Tool Permissions"],
            "row_transcripts": ["zh": "会话记录", "en": "Transcripts"],
            "row_ssh": ["zh": "SSH 远程连接", "en": "SSH Remote"],
            "row_search": ["zh": "内置智能搜索", "en": "Smart Search"],
            "row_browser": ["zh": "内置浏览器", "en": "Built-in Browser"],
            "row_gateway": ["zh": "Gateway 设置", "en": "Gateway Settings"],
            "row_agents": ["zh": "Agents 与 Skills", "en": "Agents & Skills"],
            "row_kb": ["zh": "本机知识库", "en": "Knowledge Base"],
            "row_webhooks": ["zh": "Webhooks", "en": "Webhooks"],
            "row_icon_theme": ["zh": "图标主题", "en": "Icon Theme"],
            "row_device_fake": ["zh": "设备伪装", "en": "Device Spoof"],
            "row_audit": ["zh": "本机工具审计", "en": "Tool Audit"],
            "row_workspace": ["zh": "工作区文件", "en": "Workspace Files"],
            "row_apikeys": ["zh": "API Key 管理", "en": "API Keys"],
            "row_env": ["zh": "本机环境检测", "en": "Environment Check"],
            "row_netlog": ["zh": "网络兼容日志", "en": "Network Log"],
            "row_check_update": ["zh": "检查更新", "en": "Check Update"],
            "row_lang": ["zh": "语言 / Language", "en": "Language / 语言"],

            // ===== 子页面标题 =====
            "page_remote": ["zh": "远程控制", "en": "Remote Control"],
            "page_remote_sub": ["zh": "AI 控制任意 App 的 UI：读取界面、点击、输入、滑动", "en": "AI controls any app UI: read, tap, type, swipe"],
            "page_inject": ["zh": "注入与自动化", "en": "Injection & Automation"],
            "inject_subtitle": ["zh": "{n} 个应用 · 搜索/分类/版本/索引", "en": "{n} apps · search / category / version / index"],
            "inject_refresh_hint": ["zh": "点击右上角刷新", "en": "Tap refresh in the top right"],
            "inject_emergency": ["zh": "🚑 紧急恢复（Residue 式）", "en": "🚑 Emergency Recovery (Residue-style)"],
            "inject_emergency_tip": ["zh": "App 注入后打不开 → 先「一键全恢复」；仍不行再「清理残留」。不要卸载重装（会丢数据）。", "en": "App won't open after injection? Run 'Restore All' first; if still broken, 'Clean Residuals'. Don't uninstall & reinstall (data loss)."],
            "inject_restore_all": ["zh": "一键全恢复", "en": "Restore All"],
            "inject_cleanup_residual": ["zh": "清理残留", "en": "Clean Residuals"],
            "page_inject_sub": ["zh": "dylib 注入 · 应用列表 · 自动化策略", "en": "dylib injection · apps · automation"],
            "page_downloads": ["zh": "下载管理", "en": "Downloads"],
            "page_downloads_sub": ["zh": "线上编译产物 · 勾选删除 · 安装", "en": "Build artifacts · select & delete · install"],
            "page_audit": ["zh": "本机工具审计", "en": "Tool Audit"],
            "page_audit_sub": ["zh": "工具调用记录 · 成功/失败 · 导出给 AI", "en": "Tool calls · success/fail · export to AI"],
            "page_workspace": ["zh": "工作区", "en": "Workspace"],
            "page_workspace_sub": ["zh": "像文件夹一样点开 · 预览 · 复制路径", "en": "Browse like a folder · preview · copy path"],
            "page_netlog": ["zh": "网络兼容日志", "en": "Network Log"],
            "page_netlog_sub": ["zh": "中转站兼容性 · 降级记录", "en": "Relay compatibility & fallback log"],
            "page_dev_instr": ["zh": "开发者指令", "en": "Developer Instructions"],
            "page_dev_instr_sub": ["zh": "编辑 · 复制 · 设置默认 · 注入 AI 行为", "en": "Edit · copy · set default · shape AI behavior"],
            "page_automation": ["zh": "自动化中心", "en": "Automation Center"],
            "page_automation_sub": ["zh": "定时任务 · 历史 · 重试", "en": "Scheduled tasks · history · retry"],
            "page_tool_policy": ["zh": "工具权限策略", "en": "Tool Permissions"],
            "page_tool_policy_sub": ["zh": "按工具控制 · 真实/占位 · 搜索即授权", "en": "Per-tool control · real/stub · search-to-authorize"],
            "page_transcripts": ["zh": "会话记录", "en": "Transcripts"],
            "page_transcripts_sub": ["zh": "完整对话存档 · 导出", "en": "Full chat archive · export"],
            "page_search": ["zh": "内置智能搜索", "en": "Smart Search"],
            "page_search_sub": ["zh": "Bing Web 搜索 · 用法说明", "en": "Bing web search · usage"],
            "page_gateway": ["zh": "Gateway 设置", "en": "Gateway Settings"],
            "page_gateway_sub": ["zh": "服务端管理 · 远程接入", "en": "Server management · remote access"],
            "page_agents": ["zh": "Agents 与 Skills", "en": "Agents & Skills"],
            "page_agents_sub": ["zh": "隔离指令 · 技能 · 工作流", "en": "Isolated prompts · skills · workflows"],
            "page_kb": ["zh": "本机知识库", "en": "Knowledge Base"],
            "page_kb_sub": ["zh": "文件导入 · 来源检索 · 问答增强", "en": "Import files · source search · RAG"],
            "page_webhooks": ["zh": "Webhooks", "en": "Webhooks"],
            "page_webhooks_sub": ["zh": "HTTPS 事件出口 · 订阅管理", "en": "HTTPS event output · subscriptions"],
            "page_data": ["zh": "数据管理", "en": "Data Management"],
            "page_data_sub": ["zh": "App 文稿目录 · 备份与清理", "en": "App Documents · backup & clean"],
            "page_capabilities": ["zh": "权限与自动化", "en": "Permissions & Automation"],
            "page_capabilities_sub": ["zh": "系统能力检测 · 权限开关", "en": "System capabilities · permission toggles"],
            "page_apikeys": ["zh": "API Key 管理", "en": "API Keys"],
            "page_apikeys_sub": ["zh": "查看 · 显隐 · 恢复", "en": "View · show/hide · recover"],
            "page_ssh": ["zh": "SSH 远程连接", "en": "SSH Remote"],
            "page_ssh_sub": ["zh": "Linux 远程命令 · 文件传输", "en": "Remote Linux commands · file transfer"],
            "page_env": ["zh": "本机环境检测", "en": "Environment Check"],
            "page_env_sub": ["zh": "TrollStore · 权限 · 注入链路", "en": "TrollStore · permissions · injection chain"],

            // ===== 常用按钮 =====
            "btn_install": ["zh": "安装", "en": "Install"],
            "btn_export": ["zh": "导出", "en": "Export"],
            "btn_import": ["zh": "导入", "en": "Import"],
            "btn_new": ["zh": "新建", "en": "New"],
            "btn_edit": ["zh": "编辑", "en": "Edit"],
            "btn_retry": ["zh": "重试", "en": "Retry"],
            "btn_stop": ["zh": "停止", "en": "Stop"],
            "btn_test": ["zh": "测试", "en": "Test"],
            "btn_clear": ["zh": "清空", "en": "Clear"],
            "btn_save_config": ["zh": "保存配置", "en": "Save Config"],
            "btn_check_connection": ["zh": "检查连接", "en": "Check Connection"],
            "status_connected": ["zh": "已连接", "en": "Connected"],
            "status_disconnected": ["zh": "未连接", "en": "Disconnected"],
            "status_checking": ["zh": "检查中...", "en": "Checking..."],
            "ui_148": ["zh": "原因：%@", "en": "Reason: %@"],
            "ui_149": ["zh": "建议：%@", "en": "Suggestion: %@"],
            "ui_150": ["zh": "%@ 失败", "en": "%@ failed"],
            "ui_151": ["zh": "成功 %@", "en": "Success %@"],
            "ui_152": ["zh": "·均耗 %@ms", "en": "· avg %@ms"],
            "ui_153": ["zh": "主导错误 %@", "en": "Top error %@"],
            "ui_154": ["zh": "最近失败：%@", "en": "Latest failure: %@"],
            "ui_155": ["zh": "%@ 个", "en": "%@ apps"],
            "ui_156": ["zh": "%@ 次 · 成功 %@", "en": "%@ runs · %@ OK"],
            "ui_157": ["zh": "第 %@/%@ 轮", "en": "Round %@/%@"],
            "ui_158": ["zh": "执行过程（%@ 步）", "en": "Execution (%@ steps)"],
            "ui_159": ["zh": "型号标识 %@ · %@ · %@ · %@", "en": "Model %@ · %@ · %@ · %@"],
            "ui_160": ["zh": "扫描 %@ 的可清理项", "en": "Scanning %@ for cleanables"],
            "ui_161": ["zh": "无法扫描 %@", "en": "Cannot scan %@"],
            "ui_162": ["zh": "未找到该 App 或数据容器不可访问\n（TrollStore 需开启 AppDataContainers 权限）", "en": "App not found or container inaccessible\n(TrollStore needs AppDataContainers entitlement)"],
            "ui_163": ["zh": "可用 %@ / 总 %@", "en": "Free %@ / total %@"],
            "ui_164": ["zh": "%@ 个", "en": "%@ apps"],
            "ui_165": ["zh": "级别 %@", "en": "Level %@"],
            "ui_166": ["zh": "线上编译产物会保存在\nDocuments/Workspace/downloads/", "en": "Online build artifacts are saved in\nDocuments/Workspace/downloads/"],
            "ui_167": ["zh": "文件过大（%@），仅显示前 64KB", "en": "File too large (%@), showing first 64KB only"],
            "ui_168": ["zh": "%@ 元素", "en": "%@ elements"],
            "ui_169": ["zh": "✅ 已切换到「%@」，主屏幕图标稍后更新", "en": "✅ Switched to “%@”, home icon updates shortly"],
            "ui_170": ["zh": "名称: %@\n模型: %@\n接口: %@\n\n确认导入并立即使用？", "en": "Name: %@\nModel: %@\nBase URL: %@\n\nImport and use now?"],
            "ui_171": ["zh": "已选 %@", "en": "Selected %@"],
            "ui_0": ["zh": "AI 可用 browser.snapshot", "en": "AI can use browser.snapshot"],
            "ui_1": ["zh": "AI 用 browser.* 控制", "en": "AI controls via browser.*"],
            "ui_2": ["zh": "Agents 通过 agents.json 配置，放入 KnowledgeBase 目录即可加载。", "en": "Agents are configured via agents.json; place it in the KnowledgeBase folder to load."],
            "ui_3": ["zh": "App 会在请求被中转站拒绝或超时时自动逐级简化请求参数（降级），成功后记住可用级别。级别 5 走 Responses API（Codex 同款端点），可保留工具调用；级别 ≥3 表示仅可纯对话。", "en": "The app auto-degrades request params step by step when the relay rejects or times out; the working level is remembered. Level 5 uses the Responses API (Codex endpoint) and keeps tool calls; levels >=3 mean chat-only."],
            "ui_4": ["zh": "App 内置行为规范 · 不可编辑 · 切换立即生效", "en": "Built-in behavior rules · read-only · takes effect immediately"],
            "ui_5": ["zh": "App 注入后打不开 → 先「一键全恢复」；仍不行再「清理残留」。不要卸载重装（会丢数据）。", "en": "If an app won't open after injection → try 'Restore All' first; then 'Clean Residuals'. Don't uninstall & reinstall (loses data)."],
            "ui_6": ["zh": "Gateway 服务端运行在 Mac/Linux/NAS 上，通过 WebSocket 配对。连接后可远程调用手机工具、下发定时任务。", "en": "Gateway runs on Mac/Linux/NAS, paired over WebSocket. Once connected you can call phone tools remotely and schedule tasks."],
            "ui_7": ["zh": "Max Tokens：单次回复最多生成的 token 数（输出上限，不限制上下文）。", "en": "Max Tokens: max output tokens per reply (output cap, does not limit context)."],
            "ui_8": ["zh": "TrollAgent 自身也会同步保活，切后台继续执行远程控制任务", "en": "TrollAgent keeps itself alive too, continuing remote-control tasks in background"],
            "ui_9": ["zh": "TrollStore 已安装 · 清理能力可用", "en": "TrollStore installed · cleanup available"],
            "ui_10": ["zh": "github.com → Settings → Developer settings → Personal access tokens → Tokens (classic) 生成，勾选 repo 与 workflow 权限。", "en": "Generate at github.com → Settings → Developer settings → Personal access tokens → Tokens (classic), check repo & workflow scopes."],
            "ui_11": ["zh": "v2.9.79：双引擎检索——Bing 优先，失败自动回退 DuckDuckGo（均免 Key）。AI 可先用 web.search 拿标题/链接/摘要，再用 web.fetch 抓取网页原文深入阅读，回答时效性问题更准确。", "en": "v2.9.79: dual-engine search — Bing first, auto-fallback to DuckDuckGo (no key needed). AI can get titles/links/summaries via web.search, then read the full page with web.fetch for time-sensitive answers."],
            "ui_12": ["zh": "• 两者同时生效，系统指令先注入，开发者指令后注入", "en": "• Both apply; system prompt is injected first, developer instructions after"],
            "ui_13": ["zh": "• 开发者指令：用户可自建/编辑，作为补充规范", "en": "• Developer instructions: user-created/edited, used as supplemental rules"],
            "ui_14": ["zh": "• 系统指令：App 内置，不可编辑，优先级最高，控制 AI 的基本行为模式", "en": "• System prompt: built-in, read-only, highest priority, controls AI base behavior"],
            "ui_15": ["zh": "① 选择目标 App", "en": "① Pick target App"],
            "ui_16": ["zh": "② 选择伪装机型", "en": "② Pick fake device model"],
            "ui_17": ["zh": "「真实」= 有实际执行逻辑；「占位」= 仅注册了接口、未接入真实功能。", "en": "'Real' = has actual logic; 'Stub' = interface registered only, no real function yet."],
            "ui_18": ["zh": "上下文预算：发送给模型的上下文 token 上限。会话超出时自动裁剪最早的历史消息（保留最近对话），避免长会话请求过大变慢或超时。", "en": "Context budget: max context tokens sent to the model. When exceeded, the oldest messages are auto-trimmed (keeping recent chat) to avoid slow/oversized requests."],
            "ui_19": ["zh": "专业释放设备存储空间", "en": "Pro storage cleanup"],
            "ui_20": ["zh": "主机地址", "en": "Host"],
            "ui_21": ["zh": "主页", "en": "Home"],
            "ui_22": ["zh": "仅用于本轮请求，本机准备", "en": "This round only, prepared locally"],
            "ui_23": ["zh": "仓库与 workflow 设置", "en": "Repo & workflow settings"],
            "ui_24": ["zh": "使用说明", "en": "Usage"],
            "ui_25": ["zh": "供应商快速配置", "en": "Quick provider presets"],
            "ui_26": ["zh": "保存修改", "en": "Save changes"],
            "ui_27": ["zh": "保存并测试连接", "en": "Save & test connection"],
            "ui_28": ["zh": "保存配置", "en": "Save config"],
            "ui_29": ["zh": "健康度", "en": "Health"],
            "ui_30": ["zh": "全部成功", "en": "All OK"],
            "ui_31": ["zh": "切换中…", "en": "Switching…"],
            "ui_32": ["zh": "初始请求只加载常驻核心工具（标 ★，无需搜索），其余工具由 AI 用「工具搜索」按需加载，搜索命中即自动放行本会话、无弹窗。常驻核心始终可用，无需在此配置。", "en": "Initial requests only load the resident core tools (marked ★, no search needed); other tools are loaded on demand by AI via 'tool search', auto-authorized for this session on hit. Resident cores are always available."],
            "ui_33": ["zh": "删除", "en": "Delete"],
            "ui_34": ["zh": "删除所选", "en": "Delete selected"],
            "ui_35": ["zh": "加载中…", "en": "Loading…"],
            "ui_36": ["zh": "单独恢复（还原注入前）", "en": "Restore this app (pre-injection)"],
            "ui_37": ["zh": "单独清理残留", "en": "Clean residuals"],
            "ui_38": ["zh": "原理（v2.9.93）：默认内存注入——App 运行时用 opainject 加载 FakeDevice.dylib，读取 fake_device.json 替换 UIDevice 返回的机型/名称/系统版本。不改任何文件、零残留，App 重启即还原；恢复 = 点还原（杀进程重启）。部分 App 通过 sysctl 读硬件标识，无法被 UIDevice 层覆盖。", "en": "How it works (v2.9.93): memory injection by default — loads FakeDevice.dylib via opainject at runtime, reads fake_device.json to override model/name/system version returned by UIDevice. No files changed, zero residue, restored on app restart; restore = tap restore (kills & relaunches). Apps reading hardware IDs via sysctl cannot be covered at UIDevice layer."],
            "ui_39": ["zh": "发送测试事件", "en": "Send test event"],
            "ui_40": ["zh": "取消", "en": "Cancel"],
            "ui_41": ["zh": "只读", "en": "Read-only"],
            "ui_42": ["zh": "启用注入", "en": "Enable injection"],
            "ui_43": ["zh": "在授权页粘贴验证码并确认，成功后 App 会自动关闭浏览器并完成登录，无需手动操作。", "en": "Paste the code on the auth page and confirm; the app auto-closes the browser and completes login."],
            "ui_44": ["zh": "好", "en": "OK"],
            "ui_45": ["zh": "审计记录已导出", "en": "Audit log exported"],
            "ui_46": ["zh": "密码", "en": "Password"],
            "ui_47": ["zh": "密钥仅保存在本机 UserDefaults，不会上传。恢复到新设备需重新输入。", "en": "Keys are stored locally in UserDefaults only; re-enter them after restoring to a new device."],
            "ui_48": ["zh": "导入", "en": "Import"],
            "ui_49": ["zh": "导入模型配置？", "en": "Import model config?"],
            "ui_50": ["zh": "尚未添加模型配置", "en": "No model configs yet"],
            "ui_51": ["zh": "工具结果", "en": "Tool result"],
            "ui_52": ["zh": "已保存到本机", "en": "Saved locally"],
            "ui_53": ["zh": "已内置默认 Client ID，新手无需改动（留空 = 使用内置默认，删空保存也会自动恢复）。高级用户可覆盖为自己注册的 OAuth App：github.com → Settings → Developer settings → OAuth Apps → New OAuth App（勾选 Enable Device Flow），复制 Client ID 填入。", "en": "Built-in default Client ID included; beginners can leave it empty (empty = use the default, deleting and saving also restores it). Advanced users can override with their own OAuth App: github.com → Settings → Developer settings → OAuth Apps → New OAuth App (enable Device Flow), fill in the Client ID."],
            "ui_54": ["zh": "已用", "en": "Used"],
            "ui_55": ["zh": "帮我搜一下 2026 年最新的 iPhone 发布消息", "en": "Search for the latest 2026 iPhone announcements"],
            "ui_56": ["zh": "常驻", "en": "Resident"],
            "ui_57": ["zh": "彻底移除", "en": "Remove fully"],
            "ui_58": ["zh": "快速清理", "en": "Quick clean"],
            "ui_59": ["zh": "思考过程", "en": "Thinking"],
            "ui_60": ["zh": "总览", "en": "Overview"],
            "ui_61": ["zh": "恢复备份（.troll-fools.bak）", "en": "Restore backup (.troll-fools.bak)"],
            "ui_62": ["zh": "打开", "en": "Open"],
            "ui_63": ["zh": "执行", "en": "Run"],
            "ui_64": ["zh": "执行中…", "en": "Running…"],
            "ui_65": ["zh": "批准执行", "en": "Approve"],
            "ui_66": ["zh": "技能是预置的工作流指令。保存后 AI 可用 skills.list 发现、skills.read 读取并按指令执行。", "en": "Skills are preset workflow instructions. After saving, AI can discover via skills.list, read via skills.read and follow them."],
            "ui_67": ["zh": "技能是预置的工作流指令：AI 可用 skills.list 发现、skills.read 读取并执行。可在本页启用/停用/删除，或点 + 新建。", "en": "Skills are preset workflow instructions: AI can discover via skills.list, read and execute via skills.read. Enable/disable/delete here, or tap + to create."],
            "ui_68": ["zh": "拒绝", "en": "Reject"],
            "ui_69": ["zh": "按供应商", "en": "By provider"],
            "ui_70": ["zh": "按需", "en": "On demand"],
            "ui_71": ["zh": "授权页已打开，验证码已自动复制到剪贴板", "en": "Auth page opened; code copied to clipboard"],
            "ui_72": ["zh": "提速提示：Max Tokens 是输出上限，值越大模型单次生成越长、等待越久。日常对话 2048 已够用；若回复慢，可调低 Max Tokens 或上下文预算。", "en": "Tip: Max Tokens is the output cap — larger values make each generation longer and slower. 2048 is enough for daily chat; if replies are slow, lower Max Tokens or the context budget."],
            "ui_73": ["zh": "搜索词会发送到 Bing / DuckDuckGo，用于返回检索结果。不会上传对话历史。", "en": "Search terms are sent to Bing / DuckDuckGo for results. Chat history is not uploaded."],
            "ui_74": ["zh": "收起键盘", "en": "Dismiss keyboard"],
            "ui_75": ["zh": "文件日志", "en": "File logs"],
            "ui_76": ["zh": "暂无 Gateway 服务端，点右上角 + 添加", "en": "No Gateway yet, tap + to add"],
            "ui_77": ["zh": "暂无下载", "en": "No downloads"],
            "ui_78": ["zh": "暂无任务", "en": "No tasks"],
            "ui_79": ["zh": "暂无助手角色，点右上角 + 新建", "en": "No assistant roles yet, tap + to create"],
            "ui_80": ["zh": "暂无历史会话记录", "en": "No session history"],
            "ui_81": ["zh": "暂无启用的自动化任务", "en": "No enabled automation tasks"],
            "ui_82": ["zh": "暂无失败记录", "en": "No failure records"],
            "ui_83": ["zh": "暂无审计日志", "en": "No audit logs"],
            "ui_84": ["zh": "暂无工具调用记录", "en": "No tool call records"],
            "ui_85": ["zh": "暂无待批准操作", "en": "No pending approvals"],
            "ui_86": ["zh": "暂无执行记录", "en": "No execution records"],
            "ui_87": ["zh": "暂无技能，点右上角 + 新建", "en": "No skills yet, tap + to create"],
            "ui_88": ["zh": "暂无模型配置", "en": "No model configs"],
            "ui_89": ["zh": "暂无知识库文件", "en": "No knowledge base files"],
            "ui_90": ["zh": "暂无自动化任务", "en": "No automation tasks"],
            "ui_91": ["zh": "暂无自定义 Agent", "en": "No custom Agents"],
            "ui_92": ["zh": "暂无记录", "en": "No records"],
            "ui_93": ["zh": "暂无记录。发起一次对话后，这里会显示每次请求的载荷级别与结果。", "en": "No records yet. After a chat, each request's level and result appears here."],
            "ui_94": ["zh": "暂无运行中的任务", "en": "No running tasks"],
            "ui_95": ["zh": "暂无附件", "en": "No attachments"],
            "ui_96": ["zh": "最近请求（最多 30 条）", "en": "Recent requests (max 30)"],
            "ui_97": ["zh": "服务端", "en": "Server"],
            "ui_98": ["zh": "未登录", "en": "Not logged in"],
            "ui_99": ["zh": "机制", "en": "How it works"],
            "ui_100": ["zh": "模型配置导入", "en": "Import model config"],
            "ui_101": ["zh": "正在检测本机环境…", "en": "Checking device environment…"],
            "ui_102": ["zh": "此目录为空", "en": "This folder is empty"],
            "ui_103": ["zh": "注入 FakeDevice 并重启 App…", "en": "Injecting FakeDevice & restarting App…"],
            "ui_104": ["zh": "注入 TrollMCPAgent v4（安全版）", "en": "Inject TrollMCPAgent v4 (safe)"],
            "ui_105": ["zh": "测试接口延迟", "en": "Test latency"],
            "ui_106": ["zh": "添加内容", "en": "Add content"],
            "ui_107": ["zh": "清空", "en": "Clear"],
            "ui_108": ["zh": "温度", "en": "Temperature"],
            "ui_109": ["zh": "点右上角刷新获取上游模型列表", "en": "Tap refresh (top-right) to fetch upstream models"],
            "ui_110": ["zh": "状态", "en": "Status"],
            "ui_111": ["zh": "环境自检", "en": "Environment check"],
            "ui_112": ["zh": "用户名", "en": "Username"],
            "ui_113": ["zh": "登录成功 ✓", "en": "Logged in ✓"],
            "ui_114": ["zh": "真后台保活", "en": "True background keep-alive"],
            "ui_115": ["zh": "确认执行", "en": "Confirm"],
            "ui_116": ["zh": "禁用注入", "en": "Disable injection"],
            "ui_117": ["zh": "私钥路径", "en": "Private key path"],
            "ui_118": ["zh": "移除注入（还原）", "en": "Remove injection (restore)"],
            "ui_119": ["zh": "端口", "en": "Port"],
            "ui_120": ["zh": "等待授权…", "en": "Waiting for auth…"],
            "ui_121": ["zh": "系统清理", "en": "System cleanup"],
            "ui_122": ["zh": "线上编译在指定仓库的 Actions 中运行。仓库须包含 build-tweak workflow，且当前账号对该仓库有写权限。授权新账号成功后，Owner 会自动填入该账号（若此前仍是默认值）。", "en": "Online builds run in the Actions of the chosen repo. The repo must contain the build-tweak workflow and your account needs write access. After authorizing a new account, Owner auto-fills to that account (if it was still the default)."],
            "ui_123": ["zh": "缓存 · 钥匙串 · 广告符 · 数据容器 · 标识符", "en": "Caches · Keychain · IDFA · Containers · Identifiers"],
            "ui_124": ["zh": "缓存占用", "en": "Cache usage"],
            "ui_125": ["zh": "编译模式允许在 iPhone 上编译 dylib。需要已注入 TMBuildAgent.dylib 到 TrollMCP。编译令牌用于验证编译请求。", "en": "Build mode compiles dylibs on iPhone. Requires TMBuildAgent.dylib injected into TrollMCP. The build token is used to verify build requests."],
            "ui_126": ["zh": "自动化中心支持脚本执行、定时任务（cron）、事件触发。通过 MCP 工具 automation.* 和 cron.fire 驱动。", "en": "Automation hub supports script execution, cron jobs and event triggers, driven by the automation.* and cron.fire MCP tools."],
            "ui_127": ["zh": "自动化任务", "en": "Automation tasks"],
            "ui_128": ["zh": "获取上游模型列表", "en": "Fetch upstream models"],
            "ui_129": ["zh": "蓝框", "en": "Blue box"],
            "ui_130": ["zh": "触发中…", "en": "Triggering…"],
            "ui_131": ["zh": "认证方式（二选一）", "en": "Auth method (pick one)"],
            "ui_132": ["zh": "说明", "en": "Info"],
            "ui_133": ["zh": "说明：TrollStore 安装的 App 同样支持动态图标切换（CFBundleAlternateIcons）。若切换后桌面图标未变，请重启一次桌面（锁屏重开）。", "en": "Note: TrollStore apps also support dynamic icon switching (CFBundleAlternateIcons). If the home-screen icon does not change after switching, restart the springboard once (lock & unlock)."],
            "ui_134": ["zh": "请选择", "en": "Please select"],
            "ui_135": ["zh": "调用记录", "en": "Call log"],
            "ui_136": ["zh": "还没有开发者指令，点右上角 + 新建。", "en": "No developer instructions yet, tap + to create."],
            "ui_137": ["zh": "连接信息", "en": "Connection"],
            "ui_138": ["zh": "适用于 OpenAI、DeepSeek OpenAI 格式和多数兼容网关。Base URL 通常以 /v1 结尾。", "en": "Works with OpenAI, DeepSeek OpenAI-format and most compatible gateways. Base URL usually ends with /v1."],
            "ui_139": ["zh": "选择图标主题，立即生效（无需重新安装）", "en": "Pick an icon theme, applies immediately (no reinstall needed)"],
            "ui_140": ["zh": "配置后，AI 可通过 ssh.exec 工具在远程 Linux 服务器执行命令，通过 ssh.scp 传输文件。适用于线上编译、服务器管理、文件同步等场景。", "en": "After setup, AI can run commands on a remote Linux server via ssh.exec and transfer files via ssh.scp. Great for online builds, server management, file sync."],
            "ui_141": ["zh": "重新检测", "en": "Re-check"],
            "ui_142": ["zh": "零配置：点下方按钮，App 内置浏览器打开 GitHub 授权页，登录授权后自动完成，无需复制 Token、无需注册任何东西。任意 GitHub 账号都能用。", "en": "Zero config: tap the button below, the built-in browser opens the GitHub auth page; login & authorize and it's done — no token copying, nothing to register. Any GitHub account works."],
            "ui_143": ["zh": "首次调用系统能力时会请求对应权限。未授权的工具调用将返回错误信息。", "en": "System capabilities request permission on first use. Unauthorized tool calls return an error."],
            "ui_144": ["zh": "默认", "en": "Default"],
            "ui_145": ["zh": "默认指令会注入 AI 请求。可写：工程约定、代码风格、工具使用偏好、回复格式要求等。", "en": "Default instructions are injected into every AI request. You can write: project conventions, code style, tool usage preferences, reply format requirements, etc."],
            "ui_146": ["zh": "默认指令（标「默认」）会在每次 AI 请求时作为 system 消息注入，AI 将遵循其中的约定。长按指令可设默认/编辑/删除。", "en": "Default instructions (marked 'Default') are injected as system messages in every AI request and AI follows them. Long-press a instruction to set default / edit / delete."],
            "ui_147": ["zh": "🚑 紧急恢复（Residue 式）", "en": "🚑 Emergency restore (Residue-style)"],
            // v2.9.139：AI 控制中心
            "ui_172": ["zh": "AI 控制中心", "en": "AI Control Center"],
            "ui_173": ["zh": "执行计划", "en": "Plan"],
            "ui_174": ["zh": "执行日志", "en": "Execution Log"],
            "ui_175": ["zh": "执行结果", "en": "Result"],
            "ui_176": ["zh": "现场截图", "en": "Live Screenshot"],
            "ui_177": ["zh": "关闭", "en": "Close"],
            "ui_178": ["zh": "执行中", "en": "Running"],
            "ui_179": ["zh": "已完成", "en": "Done"],
            "ui_180": ["zh": "未开始", "en": "Idle"],
            "ui_181": ["zh": "控制已结束", "en": "Control finished"],
            "ui_183": ["zh": "操作宏", "en": "Macros"],
            "ui_184": ["zh": "新建宏", "en": "New Macro"],
            "ui_185": ["zh": "宏名称（如 每日打卡）", "en": "Macro name (e.g. daily check-in)"],
            "ui_186": ["zh": "名称不能为空", "en": "Name cannot be empty"],
            "ui_187": ["zh": "开始录制：去聊天让 AI 操作，完成后回来点「停止」或喊 AI 调 macro.stop", "en": "Recording started: ask AI to operate in chat, then tap Stop or call macro.stop"],
            "ui_188": ["zh": "录制中", "en": "Recording"],
            "ui_189": ["zh": "停止并保存", "en": "Stop & Save"],
            "ui_190": ["zh": "还没有宏", "en": "No macros yet"],
            "ui_191": ["zh": "点右上角「录制」新建：让 AI 操作一遍（点/滑/输入），自动录成宏，以后一键回放", "en": "Tap record: let AI operate once (tap/swipe/type), it becomes a replayable macro"],
            "ui_192": ["zh": "录制新宏", "en": "Record New Macro"],
            "ui_193": ["zh": "步", "en": "steps"],
            "ui_194": ["zh": "创建于", "en": "Created"],
            "ui_195": ["zh": "删除", "en": "Delete"],
            "ui_182": ["zh": "控制会话已结束，可查看结果", "en": "Control session finished, see result below"],
        ]
        return table[key]?[lang] ?? key
    }

    /// v2.9.136：带参数模板（与 UI 插值文案配套，%@ 占位，String(format:) 桥接）
    static func t(_ key: String, _ args: CVarArg...) -> String {
        let base = t(key)
        return String(format: base, arguments: args)
    }
}